version: "2"
services:
  ui:
    build: ./ui
    stdin_open: true #putting this here because it breaks with react-scripts@3.4.1
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:11.9
    container_name: chat-app-postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql